### PR TITLE
Fix #2: Fix the Edit on Github links

### LINKED ISSUE #2: Fix the "Edit on Github" links
Currently, we point users to the Wiki, we should point to the `/develop/docs` folder.

_Note: Special handling of the index page is needed._

### PR DESCRIPTION
**Pull request by petrdvorak**

### CODE REVIEW

**Comment by petrdvorak** [comment]
@hvge @romanstrobl I noticed that mobile libraries use `Readme.md` instead of `Home.md`. Looking at the repository, this seems to be better, since the `docs` folder will render the `Readme.md` file in the bottom. We need to unify this, otherwise, we will not be able to do reasonable templating in our Developer Portal (we are not able to reliably check which of the options is used.)

**Comment by romanstrobl** [comment]
Yes, we can switch to `Readme.md` in backend projects.

**Comment by hvge** [comment]
Let's switch everything to `Readme.md`. The DocuCheck tool can deal with this easily.

**Comment by petrdvorak** [comment]
@hvge This needs to actually be fixed in the Github repos themselves, just as the other issue I submitted with the filename case. The issue is with links from developer portal back to Github...

**Comment by petrdvorak** [comment]
@hvge @romanstrobl I updated the code to point to `Readme.md` and to use `View on Github` text.

**Pull request merged**
